AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 3

Parameters:
  S3BucketName:
    Type: String
    Default: sample-name

Resources:
  TwilioSendReportFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.9
      Environment:
        Variables:
          S3_BUCKET_NAME: !Ref S3BucketName
          ACCOUNT_SID: "ACCOUNT_SID"
          AUTH_TOKEN: "AUTH_TOKEN"
          FLOW_TOKEN: "FLOW_TOKEN"
          TWILLIO_PHONE_NUMBER: "+TWILLIO_PHONE_NUMBER"
      Architectures:
        - x86_64
